### ISSUE TITLE
Fix links in the readthedocs

### ISSUE THREAD

**Issue by fasterius** [NBISweden/workshop-reproducible-research#1]

**Comment by verku** [comment]
Links on the welcome page are correct (master branch).

**Comment by verku** [comment]
Needs to be re-opened in case links on other pages need to be fixed

**Comment by fasterius** [comment]
Have we seen any other broken links or can we close this?

**Comment by verku** [comment]
I found the link to the Google Drive to the old lectures, will fix that in the afternoon
