### ISSUE TITLE
Fix possibly broken supplementary_material.Rmd

### ISSUE THREAD

**Issue by johnne** [NBISweden/workshop-reproducible-research#14]
I'm having problems getting the `supplementary_material.Rmd` Rmarkdown code to produce the supplementary.pdf file it should as part of the snakemake workflow.

Can some R-savvy person go through and check whether this is due to my shortcomings or an actual bug?

This is part of the error log I'm getting:

```bash
Quitting from lines 87-91 (supplementary_material.Rmd) 
Error in `[.data.frame`(meta, , columns) : undefined columns selected
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> [ -> [.data.frame

```

**Comment by johnne** [comment]
Ok if I set column names on the multiqc stats table with `colnames(qc) <- c("Percent duplicates", "Percent GC", "Avg sequence length", "Percent fails", "Total sequences")` then I'm able to generate the supplementary.pdf output in the Docker container. I have no clue why this hasn't come up earlier?

**Comment by varemo** [comment]
Is this the one in rmarkdown/ or docker/ ? The colnames of qc should already be set in the code.

**Comment by johnne** [comment]
@varemo I'm trying the one in git/code/ currently, but it's identical to the one in docker. The qc columns *are* set when the multiqc results are read, but after formatting they still don't match `c("SRR", "Percent duplicates", "Percent GC", "Avg sequence length",
             "Percent fails", "Total sequences")` which is what's being used when the qc results are plotted.

**Comment by fasterius** [comment]
I'm unclear on whether you now fixed the problem or not; I got it to run with the current Docker image (in `git/`) and the RMarkdown (in `git/code/`). Did I miss something?

**Comment by johnne** [comment]
@fasterius so you built the docker image using the `Dockerfile` under git/ on the master branch? Then just ran `snakemake`?

**Comment by fasterius** [comment]
I build using `git/Dockerfile` on `devel` (since you had made changes there) and ran the default command (_i.e._ snakemake)

**Comment by johnne** [comment]
Right, but `devel` isn't up to date with `master` since the PR that updated the miniconda installation version. Just making sure what's what. I'm building the image from `devel` now and will try to run it.

**Comment by varemo** [comment]
It's not just something silly, like a newer MultiQC output gives different colnames at import in the RMarkdown file? I mean, since manually changing the colnames as it seems you did, fixed the problem. Anyway, I think you will sort it out, sorry for butting in, but I got the notification emails automatically and was unintentionally intrigued :D Good luck!

**Comment by johnne** [comment]
@varemo no worries! :) Yes I figured out it was a newer version of MultiQC giving new column names. I've updated the rmarkdown to work with the new version and be backwards-compatible. Problem solved! (until the the column names are changed to something more surprising ;))
