### ISSUE TITLE
Double check installation instructions

### ISSUE THREAD

**Issue by verku** [NBISweden/workshop-reproducible-research#143]
A student from the Snakemake BYOC workshop sent us the following email:

"I followed the Tools for reproducible research course and had problems with Snakemake installation before (using Ubuntu in windows machine). 

For this course I followed these:

https://snakemake.readthedocs.io/en/stable/getting_started/installation.html

including mamba install, got no problems. 

Maybe this is useful for other students!"

**Comment by fasterius** [comment]
Can you ask the student to send us the exact error message(s) he got and where/when they arose, so we can troubleshoot?

**Comment by verku** [comment]
The student went to an earlier version of the course where the conda environment file still needed manual updates from the students, so our current instructions are clear and should work.

I'm keeping this issue open because ideally we should go through all installation instructions before the course to make sure all the required info is there and up to date.
