### ISSUE TITLE
Update Jupyter tutorial with latest Snakemake MRSA workflow version

### ISSUE THREAD

**Issue by verku** [NBISweden/workshop-reproducible-research#158]
The tutorial still uses results from htseq-count which was replaced with featureCounts in the snakemake tutorial.

**Comment by verku** [comment]
This affects part 8 and the extra material (integration of Jupyter with snakemake).

**Comment by johnne** [comment]
Should be taken care of with [fc02800](https://github.com/NBISweden/workshop-reproducible-research/pull/156/commits/fc02800ba8033b729ad9d3cae4900aa3de5308fe)
