### ISSUE TITLE
Add more help text to Nextflow tutorial

### ISSUE THREAD

**Issue by johnne** [NBISweden/workshop-reproducible-research#177]
In section 5 - Workflow configuration under [Command line parameters](https://github.com/NBISweden/workshop-reproducible-research/blob/devel/pages/nextflow/nextflow-5-workflow-configuration.md#command-line-parameters) when the students are asked to add a parameter for sra_ids I think some extra help text may be required to avoid risk of frustration. As far as I could tell the `ch_sra_ids` input channel is not mentioned previously in the tutorial (this is where they should use the new param I assume) which could be confusing. Also, maybe explain/give example of how to define a list in the config.

**Comment by fasterius** [comment]
Clarifications and more in-depth material has been added.
