### ISSUE TITLE
Update git text according to updated snakefile

### ISSUE THREAD

**Issue by johnne** [NBISweden/workshop-reproducible-research#189]
The main Snakefile of the MRSA workflow under both `docker/Snakefile` and `git/Snakefile` now have a pure `shell:` directive for the bowtie2 command. The Git tutorial still references the old version with a `run:` directive and changing that as part of the section on branching. It doesn't make a huge difference since the students aren't executing the workflow as part of the Git tutorial, but to make it less confusing the text should be updated.

**Comment by fasterius** [comment]
I don't understand where this is - I don't find any mention of either `run:` or `shell:` in `git-5-branches.md`. Where exactly is this supposed to be?

**Comment by johnne** [comment]
Here:

https://github.com/NBISweden/workshop-reproducible-research/blob/4b6ec4963f3e04bea423c400b1bb39ef38d896dd/pages/git/git-5-branches.md?plain=1#L46

**Comment by johnne** [comment]
Currently, the Snakefile in the git tutorial is:

```python
shell:
        """
        # This gives the base name for the genome index, i.e. "intermediate/some_id"
        # rather than "intermediate/some_id.*.bt2"
        indexBase=$(echo {input.index[0]} | sed 's/.1.bt2//g')
        bowtie2 -x $indexBase -U {input.fastq} > {output} 2> {log}
        """
```

**Comment by fasterius** [comment]
Ah, okay! I was looking for exact directives, so I didn't find it :-P A change is in devel now.
