### ISSUE TITLE
Think about changing from Singularity to Apptainer

### ISSUE THREAD

**Issue by fasterius** [NBISweden/workshop-reproducible-research#215]
Should we change using Apptainer instead of Singularity? What's the difference between them? Differences between using on different platforms?

**Comment by johnne** [comment]
Take home from preparing the 2304 version of the course is that:

- we have a clearer picture of the differences between Singularity (the project maintained by the company Sylabs) and Apptainer (the open source continuation of Singularity)
- there doesn't seem to be any difference yet between the two as far as the CLI goes
- both are difficult to install on M-chip macs

Also as a side note, I've noticed that nf-core may be moving towards changing out their `SINGULARITYENV_*` variables for `APPTAINERENV_*`, indicating that the community is starting to adopt apptainer more. Hopefully we can make a more complete change to apptainer after the summer.

**Comment by fasterius** [comment]
I agree that we should change to use Apptainer instead; even if the two pieces of software are basically the same today (at least in terms of user experience) I don't think this will hold true in the future, in which case I think going for Open Source is the better choice.

**Comment by fasterius** [comment]
Some of this is fixed in #246, but we need to go through it more in detail to make sure we found all instances of Singularity and change to Apptainer where appropriate.

**Comment by fasterius** [comment]
Fixed in #263.
