### ISSUE TITLE
Add section in Singularity on how to use Singularity inside Docker

### ISSUE THREAD

**Issue by fasterius** [NBISweden/workshop-reproducible-research#216]
With this, remove the installation instructions for Singularity, and only use it from inside Docker. This is already in the material, but should be front and center.

**Comment by johnne** [comment]
The apptainer image seems to work, I can build `my_docker_image` from `Dockerfile_slim` with `--platform linux/x86_64`, convert the image to a sif-file, transfer it to Uppmax and run it there.

The apptainer image can't be used to run the same sif-file on ARM-macs though because it was created for an AMD platform. This causes the `ERROR  : Failed to spawn stage 1` error which I think relates to something in qemu emulator.

I can also build an ARM-specific image and convert it to a sif-file with the apptainer image. But again it can't be run using the apptainer docker image. 

I think if we could build an ARM-version of the apptainer image it could be used to both build and run singularity files.

**Comment by johnne** [comment]
Doesn't look like it's possible to build an apptainer image for ARM64 architecture at the moment. At least I couldn't get the source code to build for arm64. But building from a Dockerfile for Singularity (v3.8.1) works! Of course then I also needed a Docker image for the course built for the arm64 arch. So looks like the recipe to allow M-chip macs to run through the singularity tutorial is:

1. Create a modified Snakemake workflow that uses conda packages available in the arm64 subdir of conda (switch bowtie2->bbmap, and subread->HTSeq (installed via pip)).
2. Use Docker to build a `workshop-reproducible-research` arm64 image that adds the workflow from step 1
3. Use Docker to build an arm64 image with singularity installed
4. Use the image from step 3 to convert the image built in step 2 into a *.sif file
5. Run a Docker container with the image from step 3 that runs the *.sif file from step 4, and **presto**! 😅

**Comment by fasterius** [comment]
So, what do you think we should change from the course material, as it is now? Currently we are only using Singularity from within Docker (from the latest changes), do you think this should be different? Still seems like a lot of workarounds to make Singularity work on non-Linux systems 😅

**Comment by johnne** [comment]
No I think we should keep using singularity from within Docker. I only found it a little frustrating that M-chip mac users won't be able to run `singularity pull mrsa_proj.sif docker://nbisweden/workshop-reproducible-research` **and** `singularity run mrsa_proj.sif` on their own laptops. My steps above would allow them to do that, but maybe it's enough to instruct them to take their .sif file to a HPC cluster with singularity.

**Comment by fasterius** [comment]
Okay, so in that case we would then build and maintain these images for the people who managed to install Singularity locally on their Macs. I guess it's a matter of creation + maintenance burden for those specific images - how large do you feel this is? Related, I guess we'd have to have separate code for the modified pipeline stored somewhere as well? I'm not sure I like have that kind of half-redundancy for a solution we're not sure will come into play all that often, but it's a matter of degrees here, I suppose.

I'm leaning towards just leaving it as-is, and anybody who managed to install Singularity on their arm64 Mac will just fail the two Singularity commands in the tutorial - a situation we explicitly state is problematic for a number of reasons. What do you think?

**Comment by johnne** [comment]
Yes I'm reluctantly realizing it's too much of a burdern. Let's leave as-is.

**Comment by fasterius** [comment]
Let's leave it at that, then.
