### ISSUE TITLE
snakemake-env package incompatibilities

### ISSUE THREAD

**Issue by richelbilderbeek** [NBISweden/workshop-reproducible-research#228]
Hi,

I enjoy the pre-setup of the course at [https://uppsala.instructure.com/courses/82575/pages/pre-course-setup?module_item_id=750498](https://uppsala.instructure.com/courses/82575/pages/pre-course-setup?module_item_id=750498) and everything went smooth except the thing below. As I may not be the only one, I'll report it here.

## Problem

When I do

```
mamba env create -f snakemake/environment.yml -n snakemake-env
```

I get 

```
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache


Looking for: ['python=3.10.10', 'fastqc=0.11.9', 'seqtk=1.3', 'snakemake=7.25.0', 'multiqc=1.14', 'bowtie2=2.5.1', 'tbb=2021.8.0', 'samtools=1.16', 'subread=2.0.3', 'bedtools=2.30.0', 'graphviz', 'wget', 'xorg-libxrender', 'xorg-libxpm']


Could not solve for environment specs
The following packages are incompatible
├─ python 3.10.10**  is installable and it requires
│  └─ openssl >=3.1.0,<4.0a0 , which can be installed;
└─ samtools 1.16**  is uninstallable because there are no viable options
   ├─ samtools 1.16.1 would require
   │  └─ htslib >=1.17,<1.18.0a0 , which requires
   │     └─ openssl >=1.1.1t,<1.1.2a , which conflicts with any installable versions previously reported;
   └─ samtools 1.16.1 would require
      └─ htslib >=1.16,<1.17.0a0 , which requires
         └─ openssl >=1.1.1q,<1.1.2a , which conflicts with any installable versions previously reported.
```

## Expectation

I expected this to go fine.

## Process description

I have installed:

 * Ubuntu 22.0 Jammy, fully up-to-date. 

```
# Install Mambaforge3 for 64-bit Linux
curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -O 
bash Mambaforge-Linux-x86_64.sh
rm Mambaforge-Linux-x86_64.sh
```

Checking mamba is installed:

```
(base) richel@richel-latitude-7430:~$ mamba --version
mamba 1.4.1
conda 23.1.0
```

Doing the rest:

```
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```

Then the error is produced by

```
mamba env create -f snakemake/environment.yml -n snakemake-env
```

## Question

What do I do wrong? What kind of extra info would you need?

Thanks and cheers, Richel

**Comment by johnne** [comment]
Thanks for reporting this. We've removed explicit version numbers from the conda environment files for this course instance since we're having trouble finding environments that will be solvable on all computer architectures and OS used by participants. Please do a `git pull` on the main branch where you cloned the repo and try to install the environments again. This change will likely create environments with slightly different combinations of package versions for participants, but hopefully will make it possible for everyone to install the tools needed.

**Comment by richelbilderbeek** [comment]
Yup, works now, thanks! I'll close the Issue :+1: 

Keep up the good job and see you soon :-)
