### ISSUE TITLE
Nextflow splitCsv(header: true) error

### ISSUE THREAD

**Issue by johnne** [NBISweden/workshop-reproducible-research#233]
When a header is added to the samplesheet, _e.g._:

```
id,path
a,a.txt
b,b.txt
```

and the `main.nf` file contains:

```groovy
// Workflow definition
workflow {
    // Define input files
    ch_input = Channel
        .fromPath ( "first_samplesheet.csv" )
        .splitCsv(header: true)
        .map      { row -> tuple(row[0], file(row[0])) }
    // Run workflow
    CONVERT_TO_UPPER_CASE( ch_input )
}
```

I get the following error:

>N E X T F L O W  ~  version 22.10.6
Launching `main.nf` [hungry_colden] DSL2 - revision: 20f3ce4059
[-        ] process > CONVERT_TO_UPPER_CASE -
Argument of `file` function cannot be null
 -- Check script 'main.nf' at line: 9 or see '.nextflow.log' file for more details

If I change the workflow definition to:

```groovy
// Workflow definition
workflow {
    // Define input files
    ch_input = Channel
        .fromPath ( "first_samplesheet.csv" )
        .splitCsv(header: true)
        .map      { row -> tuple(row.id, file(row.path)) }
    // Run workflow
    CONVERT_TO_UPPER_CASE( ch_input )
}
```

it completes without errors. So it appears that the column names specified in the header must also be references in the map function of the channel definition?

**Comment by fasterius** [comment]
Thanks for the catch, I added more info in the tutorial now!
