### ISSUE TITLE
Re-structure file and directory hierarchy in tutorials

### ISSUE THREAD

**Issue by fasterius** [NBISweden/workshop-reproducible-research#247]
Since the discussion in https://github.com/NBISweden/NBIS-support-framework/issues/18 I thought we might think about changing some of the way we use file structure in the course at the moment. Given the final consensus (https://github.com/NBISweden/NBIS-support-framework/issues/18#issuecomment-1750455818) we can see how this differs in some cases from how we do it at the moment. Of course, that structure is just a baseline coming from the context of an NBIS support project, but I think the general discussion touched on a lot of good points regarding directory hierarchy and structure. I did add an example of this project structure along the others we show in the lecture already.

For example the **Container** tutorial we are currently using `code/`, `data/`, `intermediate` and `results/`. Given the previous discussion this could be changed to remove `intermediate/` as well as the `raw_external`/`raw_internal` division.

I haven't gone through the rest of the course yet, because I wanted to have a discussion about the proposed change first. Thoughts, @johnne ?

**Comment by johnne** [comment]
This sounds like a good idea. I had a look at the example you added to the lecture, do you suggest we keep both the first and second examples in the lecture? I guess the first should point to the support framework since it matches the `main` branch after the update?
