### ISSUE TITLE
Nextflow lecture missing params description

### ISSUE THREAD

**Issue by johnne** [NBISweden/workshop-reproducible-research#254]
https://github.com/NBISweden/workshop-reproducible-research/blob/e4e4bfacec855839a1b4b9df604e27c2921bff4b/lectures/nextflow/nextflow.qmd#L130

This line in the nextflow intro lecture uses `{params.depth}` but as far as I can tell params are not used or explained elsewhere.

**Comment by fasterius** [comment]
That particular section is meant as a fast-fire summary of some common functionality, so the explanation is purposefully omitted (parameters are explained in the 5th Nextflow tutorial page). Same thing can be said of other content in this slide, _e.g._ the `container` and `conda` directives.

Having said that, I think this is a non-issue. If you disagree we'll have to rework the lecture a bit.

**Comment by johnne** [comment]
Ok! Just wanted to check.
