### ISSUE TITLE
Make Jupyter lecture

### ISSUE THREAD

**Issue by fasterius** [NBISweden/workshop-reproducible-research#30]

**Comment by johnne** [comment]
Done, see [3f5fb9b](https://github.com/NBISweden/workshop-reproducible-research/commit/3f5fb9b7efc5d37b929c4cf3aedfcb74ef509f55#diff-e68ddbbe2adc2890c44546bc03a92fcc813c1819b5552ea3e5ec1d235ac5bd0c)
