### ISSUE TITLE
Make clear what the participants should install before the course, pointing explicitly to the setup sections.

### ISSUE THREAD

**Issue by verku** [NBISweden/workshop-reproducible-research#83]

**Comment by verku** [comment]
Participants went on with the tutorials as it was not clear to them where the "setup" sections ended

**Comment by verku** [comment]
Text to make clear that only these tools need to be set up before the course:

"We kindly ask that you take some time before Monday to set up some of the required programs and files needed to participate in the course. Instructions are found in the course material:

-     Tutorial setup for Mac/Linux users or Windows users
-     Git setup
-     Conda setup
-     Docker setup for Mac users, Linux users or Windows users
-     Singularity setup for Mac users, Linux users or Windows users

Please follow the setup instructions only for these tools before Monday, you will do the setup for the remaining tools during the course."

**Comment by verku** [comment]
An option to make clear where the setup sections start and end is to use some formatting, e.g. a box for the setup sections.

**Comment by verku** [comment]
Add instructions to prepare for the project:

"At the last day, you will have the opportunity to try out the different tools on one of your own projects. In case you don't want to use a project you are currently working on, we have prepared a small-scale project for you. 
If you would like to work on your own project, it would be great if you could have the code and data ready before Friday so that you have more time for the exercise. In case your analysis project contains computationally intense steps it may be good to scale them down for the sake of the exercise. You might, for example, subset your raw data to only contain a minuscule part of its original size."

**Comment by fasterius** [comment]
This is now added to `devel`.
